<script type="text/javascript" src="/vendor/jquery/jquery-2.1.1.js"></script>
<script type="text/javascript" src="/js/pages/home/wb.parallax.min.js"></script>
<script type="text/javascript" src="/js/pages/home/wb.lazyload.min.js"></script>
<script type="text/javascript" src="/vendor/jquery/jquery.ui.effect.min.js"></script>
<script type="text/javascript" src="/vendor/jquery/jquery.ui.effect-slide.min.js"></script>
<script type="text/javascript" src="/vendor/jquery/jquery.ui.effect-drop.min.js"></script>
<script type="text/javascript" src="/vendor/jquery/jquery.ui.effect-blind.min.js"></script>
<script type="text/javascript" src="/vendor/jquery/jquery.ui.effect-size.min.js"></script>
<script type="text/javascript" src="/vendor/jquery/jquery.ui.effect-scale.min.js"></script>
<script type="text/javascript" src="/vendor/jquery/jquery.ui.effect-fade.min.js"></script>
<script type="text/javascript" src="/js/pages/home/wwb11.min.js"></script>
<script type="text/javascript" src="/js/pages/home/welcome-scroll-animations.js"></script>